29 wfp testing
ONEcampaign/bblocks_data_importers pull request #30
Opened 2024-11-18 12:24 UTC by mharoruiz

I created a notebook to document WFP basic usage and unit tests for the WFPInflation and WFPFoodSecurity classes.

2024-11-18 14:27 UTC, lpicci96 requested changes
Some initial comments. Overall great thinking through different cases. There are some redundancies and unnecessary tests though. If we test `extract_countries` we don't need to repeat tests in both objects and can focus on their specific implementation. There are some missing tests for handling the country caching and clearing the cache, as well as some other cases for the `_load_data` methods. There are some instances where `_indicators` are set to an empty dictionary which should never be the case. See other comments.

Overall a good start! 100% coverage but remember our goal isn't to test every line

2024-11-18 14:27 UTC, lpicci96 commented on tests/test_wfp/test_wfp.py
> +def test_wfp_inflation_load_data_country_not_available(wfp_inflation_pre_load):
You should also test `_load_data` when some data is already loaded and some is not

2024-11-18 14:27 UTC, lpicci96 commented on tests/test_wfp/test_wfp.py
> +def test_wfp_inflation_available_indicators_empty(wfp_inflation_post_load):
Not sure what this is testing. `_indicators` should always exist in the object. If it were an empty dictionary the extraction would fail

2024-11-18 14:27 UTC, lpicci96 commented on tests/test_wfp/test_wfp.py
> +def test_wfp_inflation_clear_cache(wfp_inflation_post_load):
there should also be a test that checks that an extraction is run correctly after `clear_cache` is called

2024-11-18 14:27 UTC, lpicci96 commented on tests/test_wfp/test_wfp.py
> +def test_wfp_foodsecurity_load_data_validation_error(wfp_foodsecurity_pre_load):
the validation module is already tested, so there is no need to test this explicitly

2024-11-22 09:52 UTC, lpicci96 commented
@mharoruiz These look good!
I made minor changes to the tests just correcting some typos and adding doc strings. I made some updates to the example notebook just to clarify some of the functionality and add information on where the data is being pulled from. Please check if you agree with the changes. 

One test which I didn't see - in the `get_data` methods, a user should be able to pass an iso3 code or the name of a country. The class deals with resolving the country names. We should test at least one instance where mixed types (iso3 and name) are passed to the method

2024-11-22 11:51 UTC, mharoruiz commented
I find your changes good! Just added tests to make sure the `get_data` class handles iso3 codes and country names.

2024-11-22 13:49 UTC, lpicci96 approved these changes

2024-11-22 13:49 UTC, lpicci96 commented
Looks good!

2024-11-22 13:49 UTC, merged